<?xml version="1.0"?>
<robot name="simple-robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="lift" value="0"/>

	<xacro:property name="wheel_radius" value=".075"/>
	<xacro:property name="wheel_width" value=".03"/>

	<xacro:property name="base_radius" value=".25"/>
	<xacro:property name="base_height" value=".1"/>

	<xacro:property name="caster_radius" value=".01"/>

	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>

	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>

	<link name="base_link">
		<visual>
			<origin xyz= "0 0 ${lift}" />
			<geometry>
				<cylinder length="${base_height}" radius="${base_radius}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin xyz= "0 0 ${lift}" />
			<geometry>
				<cylinder length="${base_height}" radius="${base_radius}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="10"/>
			<inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
		</inertial>
	</link>

	<link name="left_wheel">
		<visual>
			<origin xyz= "0 0 ${lift}" rpy= "0 1.5708 0" />
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz= "0 0 ${lift}" rpy= "0 1.5708 0" />
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="10"/>
			<inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
		</inertial>
	</link>

	<link name="right_wheel">
		<visual>
			<origin xyz= "0 0 ${lift}" rpy= "0 1.5708 0" />
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz= "0 0 ${lift}" rpy= "0 1.5708 0" />
			<geometry>
				<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="10"/>
			<inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
		</inertial>
	</link>

	<link name="front_caster">
		<visual>
			<origin xyz= "0 0 ${lift}" />
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz= "0 0 ${lift}" />
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="10"/>
			<inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
		</inertial>
	</link>

	<link name="rear_caster">
		<visual>
			<origin xyz= "0 0 ${lift}" />
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz= "0 0 ${lift}" />
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="10"/>
			<inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
		</inertial>
	</link>

	<joint name="left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_wheel"/>
		<origin xyz="${base_radius} 0 0" />
		<axis xyz= "1 0 0" />
	</joint>

	<joint name="right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_wheel"/>
		<origin xyz="${-base_radius} 0 0" />
		<axis xyz= "1 0 0" />
	</joint>

	<joint name="front_caster_joint" type="fixed">
		<parent link="base_link"/>
		<child link="front_caster"/>
		<origin xyz="0 ${-base_radius + base_radius/4} ${-base_height/2}" />
		<axis xyz= "1 0 0" />
	</joint>

	<joint name="rear_caster_joint" type="fixed">
		<parent link="base_link"/>
		<child link="rear_caster"/>
		<origin xyz="0 ${base_radius - base_radius/4} ${-base_height/2}" />
		<axis xyz= "1 0 0" />
	</joint>

	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<alwaysOn>true</alwaysOn>
			<legacyMode>true</legacyMode>
			<updateRate>20</updateRate>
			<leftJoint>left_wheel_joint</leftJoint>
			<rightJoint>right_wheel_joint</rightJoint>
			<wheelSeparation>0.4</wheelSeparation>
			<wheelDiameter>.15</wheelDiameter>
			<torque>10</torque>
			<commandTopic>cmd_vel</commandTopic>
			<odometryTopic>odom</odometryTopic>
			<odometryFrame>odom</odometryFrame>
			<robotBaseFrame>base_footprint</robotBaseFrame>
		</plugin>
	</gazebo>

</robot>